### ISSUE TITLE
How to run the API locally

### ISSUE THREAD

**Issue by pietro909** [MLRS/gabra-web#1]
Hello, thank you for sharing this amazing project!
I'm trying to run it locally, on OSX with PHP 7.0 installed.

This is the message I'm getting:

```
$ php -S localhost:8000 -t app
PHP 7.1.14 Development Server started at Mon Jul  2 14:15:54 2018
Listening on http://localhost:8000
Document root is /Users/pietrograndi/workspace/gabra-web/app
Press Ctrl-C to quit.
[Mon Jul  2 14:15:58 2018] ::1:53852 [200]: / - Can't find application core file. Please create /Users/pietrograndi/workspace/gabra-web/app/Config/core.php, and make sure it is readable by PHP. in /Users/pietrograndi/workspace/gabra-web/lib/Cake/Core/Configure.php on line 76
```

I guess there are some missing files?

**Comment by johnjcamilleri** [comment]
Hi Pietro,
There are a few steps to get it running locally. The first is, as the error message says, that you need a `core.php` file. The reason this is not in the repository is because the settings there are system-specific. But you can rename/copy the file `core.php.default` and fill in your settings there. The same applies to `database.php.default`.

Note that this repository only contains the web interface, not the database backend. For that, see the repository <https://github.com/MLRS/gabra-api>.
